name: Build with Briefcase

on:
  release:
    types: [released]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase

    - name: Update Application Version
      if: github.event_name == 'release' && github.event.action == 'released'
      run: |
        (Get-Content pyproject.toml) -replace 'version = ".*"', 'version = "${{ github.ref_name }}"' | Set-Content pyproject.toml
      shell: pwsh

    - name: Build with Briefcase
      run: briefcase create windows && briefcase build windows && briefcase package windows

    #    - name: Upload installer as an artifact
    #      uses: actions/upload-artifact@v4
    #      with:
    #        name: Spotify2YTMusic-Windows-Installer
    #        path: dist/Spotify2YTMusic-*.msi
    #
    #    - name: Download Artifact
    #      uses: actions/download-artifact@v2
    #      with:
    #        name: Spotify2YTMusic-Windows-Installer

    - name: Show files
      run: |
        ls
        ls dist

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release' && github.event.action == 'released'
      with:
        files: dist/*.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
